server:
  port: ${port:8080}

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:loan
    username: bloan
    password: bloan
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengyaodong.bloan.model